# Generated by Django 4.2.20 on 2025-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Tiny', 'Очень маленькая'), ('Small', 'Маленькая'), ('Medium', 'Средняя'), ('Large', 'Большая')], max_length=10),
        ),
    ]
